# ===== CONFIGURAÇÕES DO PROCESSO DE DADOA =====

input_data_pred:
  - bedrooms
  - bathrooms
  - sqft_living
  - sqft_lot
  - floors
  - waterfront
  - view
  - condition
  - grade
  - sqft_above
  - sqft_basement
  - yr_built
  - yr_renovated
  - zipcode
  - sqft_living15
  - sqft_lot15

input_data_train:
  - bedrooms
  - bathrooms
  - sqft_living
  - sqft_lot
  - floors
  - waterfront
  - view
  - condition
  - grade
  - sqft_above
  - sqft_basement
  - yr_built
  - yr_renovated
  - zipcode
  - sqft_living15
  - sqft_lot15
  - price

categorical_variables:
  - zipcode
  - waterfront
  - view
  - condition
  - grade

numerical_variables:
  - bedrooms
  - bathrooms
  - sqft_living
  - sqft_lot
  - floors
  - sqft_above
  - sqft_basement
  - sqft_living15

map_variables:
 - zipcode_encoded
 - view_encoded
 - condition_encoded
 - grade_encoded

rare_encode:
  - zipcode
  - view
  - condition
  - grade

temporal_vars:
  tempo_imovel : yr_built
  tempo_renovacao : yr_renovated

scale_vars:
  - sqft_living
  - sqft_lot
  - sqft_above
  - sqft_basement
  - sqft_living15
  - sqft_lot15

zipcode_encoded:
  98178: 0.0 
  98125: 1.0 
  98028: 2.0 
  98136: 3.0 
  98074: 4.0 
  98053: 5.0 
  98003: 6.0 
  98198: 7.0 
  98146: 8.0 
  98038: 9.0 
  00000: 10.0 
  98115: 11.0 
  98107: 12.0 
  98126: 13.0 
  98103: 14.0 
  98133: 15.0 
  98040: 16.0 
  98092: 17.0 
  98030: 18.0 
  98112: 19.0 
  98052: 20.0 
  98027: 21.0 
  98117: 22.0 
  98058: 23.0 
  98001: 24.0 
  98056: 25.0 
  98166: 26.0 
  98023: 27.0 
  98105: 28.0 
  98042: 29.0 
  98008: 30.0 
  98059: 31.0 
  98122: 32.0 
  98144: 33.0 
  98004: 34.0 
  98034: 35.0 
  98075: 36.0 
  98116: 37.0 
  98118: 38.0 
  98199: 39.0 
  98045: 40.0 
  98168: 41.0 
  98177: 42.0 
  98065: 43.0 
  98029: 44.0
  98006: 45.0 
  98022: 46.0 
  98033: 47.0 
  98155: 48.0 
  98031: 49.0 
  98106: 50.0 
  98072: 51.0 
  98055: 52.0
  99999: 53.0

view_encoded:
  0: 0.0
  1: 4.0
  2: 3.0
  3: 1.0
  4: 2.0
  00000: 5.0
  99999: 6.0

condition_encoded:
  3: 0.0
  4: 2.0
  5: 1.0
  00000: 3.0
  99999: 4.0

grade_encoded:
  7: 0.0
  6: 1.0
  8: 2.0
  11: 3.0
  9: 4.0
  5: 5.0
  10: 6.0
  00000: 7.0
  99999: 8.0

# ===== CONFIGURAÇÕES DO MODELO =====

trained_model_file: models/house_price_regression

target: price

r2_score_limit : 0.7

train_data_path : 'datasets/house_price.csv'

predict_data_path : 'datasets/house_price_predict.csv'

result_data_path : 'datasets/results.csv'

features:
  - sqft_living
  - sqft_lot
  - sqft_above
  - sqft_basement
  - sqft_living15
  - sqft_lot15
  - bedrooms
  - bathrooms
  - floors
  - view_encoded
  - condition_encoded
  - grade_encoded
  - tempo_imovel
  - tempo_renovacao
  - zipcode_encoded