name: Build and Push python Image to dockerhub

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    name: push docker image to hub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env :
        DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
        DOCKERHUB_PWD: ${{secrets.DOCKERHUB_PWD}}
      run: |
        docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PWD
    - name: Build & Push Docker Image
      run: |
        docker build . --file Dockerfile --tag carolzkamada/mlops:latest
        docker push carolzkamada/mlops:latest
    - name: Docker Run
      run: |
        docker run carolzkamada/mlops:latest